source "https://rubygems.org"
ruby RUBY_VERSION

# To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# Temporary fix for https://github.com/github/pages-gem/issues/752
gem "webrick", "~> 1.7"

gem 'jekyll-algolia', "1.6.0", group: :jekyll_plugins
