/* global example */
QUnit.module('Music styles', function () {
  QUnit.module('2-step garage', example);
  QUnit.module('20th-century classical music', example);
  QUnit.module('4-beat', example);
  QUnit.module('A cappella', example);
  QUnit.module('Absolute music', example);
  QUnit.module('Acid house', example);
  QUnit.module('Acid jazz', example);
  QUnit.module('Acid rock', example);
  QUnit.module('Acid techno', example);
  QUnit.module('Acid trance', example);
  QUnit.module('Acousmatic music', example);
  QUnit.module('Acoustic music', example);
  QUnit.module('Adult contemporary music', example);
  QUnit.module('African-American music', example);
  QUnit.module('African heavy metal', example);
  QUnit.module('African hip hop', example);
  QUnit.module('Afrobeat', example);
  QUnit.module('Afrobeats', example);
  QUnit.module('Afro-Cuban jazz', example);
  QUnit.module('Afroswing', example);
  QUnit.module('African popular music', example);
  QUnit.module('Aguinaldo', example);
  QUnit.module('Aleatoric music', example);
  QUnit.module('Alternative country', example);
  QUnit.module('Alternative dance', example);
  QUnit.module('Alternative hip hop', example);
  QUnit.module('Alternative metal', example);
  QUnit.module('Alternative R&B', example);
  QUnit.module('Alternative reggaeton', example);
  QUnit.module('Alternative rock', example);
  QUnit.module('Ambient music', example);
  QUnit.module('Ambient house', example);
  QUnit.module('Ambient pop', example);
  QUnit.module('Ambient techno', example);
  QUnit.module('Ambrosian chant', example);
  QUnit.module('American folk music', example);
  QUnit.module('American folk-music revival', example);
  QUnit.module('Americana', example);
  QUnit.module('Anarcho-punk', example);
  QUnit.module('Ancient music', example);
  QUnit.module('Anglican chant', example);
  QUnit.module('Anatolian rock', example);
  QUnit.module('Anti-folk', example);
  QUnit.module('Apala', example);
  QUnit.module('Appalachian music', example);
  QUnit.module('Arabesque', example);
  QUnit.module('Arabic pop music', example);
  QUnit.module('Arena rock', example);
  QUnit.module('Argentine rock', example);
  QUnit.module('Armenian chant', example);
  QUnit.module('Ars antiqua', example);
  QUnit.module('Ars nova', example);
  QUnit.module('Ars subtilior', example);
  QUnit.module('Art pop', example);
  QUnit.module('Art punk', example);
  QUnit.module('Art rock', example);
  QUnit.module('Ashik', example);
  QUnit.module('Assyrian folk/pop music', example);
  QUnit.module('Australian country music', example);
  QUnit.module('Australian hip hop', example);
  QUnit.module('Avant-funk', example);
  QUnit.module('Avant-garde music', example);
  QUnit.module('Avant-garde jazz', example);
  QUnit.module('Avant-garde metal', example);
  QUnit.module('Avant-pop', example);
  QUnit.module('Avant-prog', example);
  QUnit.module('Avant-punk', example);
  QUnit.module('Axé', example);
  QUnit.module('Azonto', example);
  QUnit.module('Bachata', example);
  QUnit.module('Baggy', example);
  QUnit.module('Baião', example);
  QUnit.module('Bakersfield sound', example);
  QUnit.module('Baila', example);
  QUnit.module('Baisha xiyue', example);
  QUnit.module('Bajourou', example);
  QUnit.module('Bal-musette', example);
  QUnit.module('Balakadri', example);
  QUnit.module('Balinese Gamelan', example);
  QUnit.module('Balearic beat', example);
  QUnit.module('Balkan brass', example);
  QUnit.module('Ballad', example);
  QUnit.module('Ballata', example);
  QUnit.module('Ballet', example);
  QUnit.module('Baltimore club', example);
  QUnit.module('Bambuco', example);
  QUnit.module('Banda music', example);
  QUnit.module('Bangsawan', example);
  QUnit.module('Bantowbol', example);
  QUnit.module('Barbershop music', example);
  QUnit.module('Barcarolle', example);
  QUnit.module('Bard (Soviet Union)', example);
  QUnit.module('Barn dance', example);
  QUnit.module('Baroque music', example);
  QUnit.module('Baroque pop', example);
  QUnit.module('Barynya', example);
  QUnit.module('Bassline', example);
  QUnit.module('Batá-rumba', example);
  QUnit.module('Batucada', example);
  QUnit.module('Baul', example);
  QUnit.module('Beach music', example);
  QUnit.module('Beat music', example);
  QUnit.module('Beatboxing', example);
  QUnit.module('Beatlesque', example);
  QUnit.module('Beautiful music', example);
  QUnit.module('Bebop', example);
  QUnit.module('Beguine', example);
  QUnit.module('Beiguan music', example);
  QUnit.module('Bel canto', example);
  QUnit.module('Bend-skin', example);
  QUnit.module('Beneventan chant', example);
  QUnit.module('Benga music', example);
  QUnit.module('Bent edge', example);
  QUnit.module('Berlin School of electronic music', example);
  QUnit.module('Bhajan', example);
  QUnit.module('Bhangra', example);
  QUnit.module('Bhangragga', example);
  QUnit.module('Big band music', example);
  QUnit.module('Big beat', example);
  QUnit.module('Big room house', example);
  QUnit.module('Biguine', example);
  QUnit.module('Bihu', example);
  QUnit.module('Biker metal', example);
  QUnit.module('Biomusic', example);
  QUnit.module('Bitpop', example);
  QUnit.module('Blackened death metal', example);
  QUnit.module('Black metal', example);
  QUnit.module('Blackgaze', example);
  QUnit.module('Black MIDI', example);
  QUnit.module('Bluegrass music', example);
  QUnit.module('Blue-eyed soul', example);
  QUnit.module('Blues', example);
  QUnit.module('Blues ballad', example);
  QUnit.module('Blues rock', example);
  QUnit.module('Bongo Flava', example);
  QUnit.module('Boogie', example);
  QUnit.module('Boogie rock', example);
  QUnit.module('Boogie-woogie', example);
  QUnit.module('Boogaloo', example);
  QUnit.module('Boi', example);
  QUnit.module('Bollywood songs', example);
  QUnit.module('Bosnian root music', example);
  QUnit.module('Bossa Nova', example);
  QUnit.module('Bothy Ballad', example);
  QUnit.module('Bounce music', example);
  QUnit.module('Bouncy techno', example);
  QUnit.module('Brass', example);
  QUnit.module('Breakbeat', example);
  QUnit.module('Breakbeat hardcore', example);
  QUnit.module('Breakcore', example);
  QUnit.module('Breakstep', example);
  QUnit.module('Brega', example);
  QUnit.module('Breton', example);
  QUnit.module('Brill Building Sound', example);
  QUnit.module('Brit funk', example);
  QUnit.module('Britpop', example);
  QUnit.module('British blues', example);
  QUnit.module('British folk rock', example);
  QUnit.module('British Invasion', example);
  QUnit.module('British hip hop', example);
  QUnit.module('British rhythm and blues', example);
  QUnit.module('British rock music', example);
  QUnit.module('British rock and roll', example);
  QUnit.module('Broken beat', example);
  QUnit.module('Brostep', example);
  QUnit.module('Brown-eyed soul', example);
  QUnit.module('Brukdown', example);
  QUnit.module('Bubblegum pop', example);
  QUnit.module('Buddhist music', example);
  QUnit.module('Bullerengue', example);
  QUnit.module('Bikutsi', example);
  QUnit.module('Bulerías', example);
  QUnit.module('Bunraku', example);
  QUnit.module('Burger-highlife', example);
  QUnit.module('Burgundian School', example);
  QUnit.module('Bush ballad', example);
  QUnit.module('Byzantine music', example);
  QUnit.module('Ca din tulnic', example);
  QUnit.module('Ca trù', example);
  QUnit.module('Cabaret', example);
  QUnit.module('Cadence-lypso', example);
  QUnit.module('Cadence rampa', example);
  QUnit.module('Cải lương', example);
  QUnit.module('Cajun music', example);
  QUnit.module('Cakewalk', example);
  QUnit.module('Calinda', example);
  QUnit.module('Čalgija', example);
  QUnit.module('Calypso music', example);
  QUnit.module('Calypso-style baila', example);
  QUnit.module('Campursari', example);
  QUnit.module('Can Can', example);
  QUnit.module('Canadian blues', example);
  QUnit.module('Candombe', example);
  QUnit.module('Canon', example);
  QUnit.module('Cantata', example);
  QUnit.module('Cante chico', example);
  QUnit.module('Cante jondo', example);
  QUnit.module('Canterbury scene', example);
  QUnit.module('Cantiñas', example);
  QUnit.module('Cantiga', example);
  QUnit.module('Canto livre', example);
  QUnit.module('Cantopop', example);
  QUnit.module('Cantu a tenore', example);
  QUnit.module('Canzone Napoletana', example);
  QUnit.module('Cape Breton fiddling', example);
  QUnit.module('Capoeira music', example);
  QUnit.module('Carimbó', example);
  QUnit.module('Cariso', example);
  QUnit.module('Carnatic music', example);
  QUnit.module('Carol', example);
  QUnit.module('Cartageneras', example);
  QUnit.module('Carnavalito', example);
  QUnit.module('Cavacha', example);
  QUnit.module('Celempungan', example);
  QUnit.module('Cello rock', example);
  QUnit.module('Celtic chant', example);
  QUnit.module('Celtic fusion', example);
  QUnit.module('Celtic metal', example);
  QUnit.module('Celtic music', example);
  QUnit.module('Celtic punk', example);
  QUnit.module('Celtic reggae', example);
  QUnit.module('Celtic rock', example);
  QUnit.module('Cha-cha-cha', example);
  QUnit.module('Chacarera', example);
  QUnit.module('Chakacha', example);
  QUnit.module('Chalga', example);
  QUnit.module('Chamamé', example);
  QUnit.module('Chamarrita', example);
  QUnit.module('Chamber music', example);
  QUnit.module('Chamber jazz', example);
  QUnit.module('Chamber pop', example);
  QUnit.module('Champeta', example);
  QUnit.module('Changüí', example);
  QUnit.module('Chanson', example);
  QUnit.module('Chant', example);
  QUnit.module('Chap hop', example);
  QUnit.module('Charanga', example);
  QUnit.module('Charanga-vallenata', example);
  QUnit.module('Charikawi', example);
  QUnit.module('Charleston (dance)', example);
  QUnit.module('Chastushka', example);
  QUnit.module('Chầu văn', example);
  QUnit.module('Chèo', example);
  QUnit.module('Chicano rock', example);
  QUnit.module("Children's music", example);
  QUnit.module('Chicago blues', example);
  QUnit.module('Chicago house', example);
  QUnit.module('Chicago soul', example);
  QUnit.module('Chicken scratch', example);
  QUnit.module('Chill-out music', example);
  QUnit.module('Chillwave', example);
  QUnit.module('Chinese music', example);
  QUnit.module('Chinese rock', example);
  QUnit.module('Chiptune', example);
  QUnit.module('Chouval bwa', example);
  QUnit.module('Chowtal', example);
  QUnit.module('Choro', example);
  QUnit.module('Christmas carol', example);
  QUnit.module('Christmas music', example);
  QUnit.module('Christian electronic', example);
  QUnit.module('Christian alternative rock', example);
  QUnit.module('Christian country music', example);
  QUnit.module('Christian hardcore', example);
  QUnit.module('Christian hip hop', example);
  QUnit.module('Christian metal', example);
  QUnit.module('Christian music', example);
  QUnit.module('Christian punk', example);
  QUnit.module('Christian rock', example);
  QUnit.module('Christian ska', example);
  QUnit.module('Chylandyk', example);
  QUnit.module('Chula', example);
  QUnit.module('Chumba', example);
  QUnit.module('Church music', example);
  QUnit.module('Chut-kai-pang', example);
  QUnit.module('Chutney music', example);
  QUnit.module('Chutney Soca', example);
  QUnit.module('Cifra', example);
  QUnit.module('Circus music', example);
  QUnit.module('Classic country', example);
  QUnit.module('Classic rock', example);
  QUnit.module('Classic female blues', example);
  QUnit.module('Classical music', example);
  QUnit.module('Classical period', example);
  QUnit.module('Close harmony', example);
  QUnit.module('Coladeira', example);
  QUnit.module('Coldwave', example);
  QUnit.module('College rock', example);
  QUnit.module('Combined rhythm', example);
  QUnit.module('Comedy music', example);
  QUnit.module('Comedy rap', example);
  QUnit.module('Comedy rock', example);
  QUnit.module('Comic opera', example);
  QUnit.module('Compas', example);
  QUnit.module('Concerto', example);
  QUnit.module('Concerto grosso', example);
  QUnit.module('Conga', example);
  QUnit.module('Conjunto', example);
  QUnit.module('Contemporary Christian music', example);
  QUnit.module('Conscious hip hop', example);
  QUnit.module('Contemporary folk music', example);
  QUnit.module('Contemporary laïka', example);
  QUnit.module('Contemporary R&B', example);
  QUnit.module('Contradanza', example);
  QUnit.module('Cool jazz', example);
  QUnit.module('Coon song', example);
  QUnit.module('Coptic music', example);
  QUnit.module('Corrido', example);
  QUnit.module('Country music', example);
  QUnit.module('Country blues', example);
  QUnit.module('Country folk', example);
  QUnit.module('Country pop', example);
  QUnit.module('Country rap', example);
  QUnit.module('Country rock', example);
  QUnit.module('Coupé-Décalé', example);
  QUnit.module('Cowpunk', example);
  QUnit.module('Crabcore', example);
  QUnit.module('Creole music', example);
  QUnit.module('Cretan', example);
  QUnit.module('Crossover thrash', example);
  QUnit.module('Crunk', example);
  QUnit.module('Crunkcore', example);
  QUnit.module('Crust punk', example);
  QUnit.module('Csárdás', example);
  QUnit.module('Cuarteto', example);
  QUnit.module('Cueca', example);
  QUnit.module('Cumbia', example);
  QUnit.module('Cumbia villera', example);
  QUnit.module('Currulao', example);
  QUnit.module('Cyber Metal', example);
  QUnit.module('Czech bluegrass', example);
  QUnit.module('Dabke', example);
  QUnit.module('Dadra', example);
  QUnit.module('Daina', example);
  QUnit.module('Dance music', example);
  QUnit.module('Dance-pop', example);
  QUnit.module('Dance-punk', example);
  QUnit.module('Dance-rock', example);
  QUnit.module('Dancehall', example);
  QUnit.module('Dangdut', example);
  QUnit.module('Danger music', example);
  QUnit.module('Dansband', example);
  QUnit.module('Danza', example);
  QUnit.module('Danzón', example);
  QUnit.module('Dappan koothu', example);
  QUnit.module('Dark ambient', example);
  QUnit.module('Dark cabaret', example);
  QUnit.module('Darkcore', example);
  QUnit.module('Dark pop', example);
  QUnit.module('Darkstep', example);
  QUnit.module('Dark wave', example);
  QUnit.module('De dragoste', example);
  QUnit.module('Deathcore', example);
  QUnit.module('Deathgrind', example);
  QUnit.module('Death industrial', example);
  QUnit.module('Death metal', example);
  QUnit.module('Death-doom', example);
  QUnit.module('Death rock', example);
  QUnit.module('Décima', example);
  QUnit.module('Delta blues', example);
  QUnit.module('Deep funk', example);
  QUnit.module('Deep house', example);
  QUnit.module('Descarga', example);
  QUnit.module('Desi', example);
  QUnit.module('Detroit blues', example);
  QUnit.module('Detroit techno', example);
  QUnit.module('Dhamar', example);
  QUnit.module('Dhrupad', example);
  QUnit.module('Dhun', example);
  QUnit.module('Diablada', example);
  QUnit.module('Digital hardcore', example);
  QUnit.module('Dirge', example);
  QUnit.module('Dirty rap', example);
  QUnit.module('Disco', example);
  QUnit.module('Disco polo', example);
  QUnit.module('Diva house', example);
  QUnit.module('Dixieland', example);
  QUnit.module('Djent', example);
  QUnit.module('Doina', example);
  QUnit.module('Dolewave', example);
  QUnit.module('Dondang Sayang', example);
  QUnit.module('Donegal fiddle tradition', example);
  QUnit.module('Dongjing', example);
  QUnit.module('Doo-wop', example);
  QUnit.module('Doom metal', example);
  QUnit.module('Downtempo', example);
  QUnit.module('Dream pop', example);
  QUnit.module('Drone metal', example);
  QUnit.module('Drill music', example);
  QUnit.module('Drone music', example);
  QUnit.module('Drum and bass', example);
  QUnit.module('Drumstep', example);
  QUnit.module('Dub music', example);
  QUnit.module('Dub techno', example);
  QUnit.module('Dubtronica', example);
  QUnit.module('Dubstep', example);
  QUnit.module('Dubstyle', example);
  QUnit.module('Dungeon synth', example);
  QUnit.module('Dunun', example);
  QUnit.module('Dunedin Sound', example);
  QUnit.module('Dutch jazz', example);
  QUnit.module('Early music', example);
  QUnit.module('East Coast hip hop', example);
  QUnit.module('Easy listening', example);
  QUnit.module('Electric blues', example);
  QUnit.module('Electro', example);
  QUnit.module('Electro backbeat', example);
  QUnit.module('Electrogrind', example);
  QUnit.module('Electro house', example);
  QUnit.module('Electro-industrial', example);
  QUnit.module('Electro swing', example);
  QUnit.module('Electroacoustic music', example);
  QUnit.module('Electroclash', example);
  QUnit.module('Electronic body music', example);
  QUnit.module('Electronic dance music', example);
  QUnit.module('Electronic music', example);
  QUnit.module('Electronic rock', example);
  QUnit.module('Electronica', example);
  QUnit.module('Electronicore', example);
  QUnit.module('Electropop', example);
  QUnit.module('Electropunk', example);
  QUnit.module('Elevator music', example);
  QUnit.module('Emo', example);
  QUnit.module('Emo hip hop', example);
  QUnit.module('Emo pop', example);
  QUnit.module('English folk music', example);
  QUnit.module('Enka', example);
  QUnit.module('Epic Metal', example);
  QUnit.module('Eremwu eu', example);
  QUnit.module('Ethereal wave', example);
  QUnit.module('Ethiopian chant', example);
  QUnit.module('Eurobeat', example);
  QUnit.module('Eurodance', example);
  QUnit.module('Euro disco', example);
  QUnit.module('Euro house', example);
  QUnit.module('Europop', example);
  QUnit.module('Eurotrance', example);
  QUnit.module('Exotica', example);
  QUnit.module('Experimental music', example);
  QUnit.module('Experimental pop', example);
  QUnit.module('Experimental rock', example);
  QUnit.module('Expressionist music', example);
  QUnit.module('Extempo', example);
  QUnit.module('Extreme metal', example);
  QUnit.module('Fado', example);
  QUnit.module('Falak music', example);
  QUnit.module('Fandango', example);
  QUnit.module('Farruca', example);
  QUnit.module('Festejo', example);
  QUnit.module('Fife and drum blues', example);
  QUnit.module('Filk music', example);
  QUnit.module('Film score', example);
  QUnit.module('Filmi', example);
  QUnit.module('Filmi-ghazal', example);
  QUnit.module('Fingerstyle', example);
  QUnit.module('Flamenco', example);
  QUnit.module('Florida breaks', example);
  QUnit.module('Folk jazz', example);
  QUnit.module('Folk metal', example);
  QUnit.module('Folk music', example);
  QUnit.module('Folk pop', example);
  QUnit.module('Folk punk', example);
  QUnit.module('Folk rock', example);
  QUnit.module('Folktronica', example);
  QUnit.module('Forró', example);
  QUnit.module('Foxtrot', example);
  QUnit.module('Freakbeat', example);
  QUnit.module('Freak folk', example);
  QUnit.module('Free improvisation', example);
  QUnit.module('Free jazz', example);
  QUnit.module('Free tekno', example);
  QUnit.module('French house', example);
  QUnit.module('Frevo', example);
  QUnit.module('Fuji music', example);
  QUnit.module('Full-on', example);
  QUnit.module('Funaná', example);
  QUnit.module('Funeral doom', example);
  QUnit.module('Funk', example);
  QUnit.module('Funk metal', example);
  QUnit.module('Funk rock', example);
  QUnit.module('Funky house', example);
  QUnit.module('Furniture music', example);
  QUnit.module('Future bass', example);
  QUnit.module('Future garage', example);
  QUnit.module('Future soul', example);
  QUnit.module('Futurepop', example);
  QUnit.module('G-funk', example);
  QUnit.module('Gaana', example);
  QUnit.module('Gabber', example);
  QUnit.module('Gagaku', example);
  QUnit.module('Ghana', example);
  QUnit.module('Gaita Zuliana', example);
  QUnit.module('Galant', example);
  QUnit.module('Gallican chant', example);
  QUnit.module('Gamelan', example);
  QUnit.module('Gamelan bebonangan', example);
  QUnit.module('Gamelan degung', example);
  QUnit.module('Gamelan gong kebyar', example);
  QUnit.module('Gamelan salendro', example);
  QUnit.module('Gamelan selunding', example);
  QUnit.module('Gamelan semar pegulingan', example);
  QUnit.module('Gammaldans', example);
  QUnit.module('Gandrung', example);
  QUnit.module('Gangsta rap', example);
  QUnit.module('Gar', example);
  QUnit.module('Garba', example);
  QUnit.module('Garage house', example);
  QUnit.module('Garage rock', example);
  QUnit.module('Garage rock revival', example);
  QUnit.module('Gato', example);
  QUnit.module('Gavotte', example);
  QUnit.module('Gender wayang', example);
  QUnit.module('Geek rock', example);
  QUnit.module('Gelineau psalmody', example);
  QUnit.module('German folk', example);
  QUnit.module('Ghazal', example);
  QUnit.module('Ghetto house', example);
  QUnit.module('Ghettotech', example);
  QUnit.module('Girl group', example);
  QUnit.module('Glam metal', example);
  QUnit.module('Glam punk', example);
  QUnit.module('Glam rock', example);
  QUnit.module('Glitch', example);
  QUnit.module('Gnawa music', example);
  QUnit.module('Go-go', example);
  QUnit.module('Goa trance', example);
  QUnit.module('Gong chime', example);
  QUnit.module('Goombay', example);
  QUnit.module('Goregrind', example);
  QUnit.module('Goshu ondo', example);
  QUnit.module('Gospel music', example);
  QUnit.module('Gospel blues', example);
  QUnit.module('Gothic metal', example);
  QUnit.module('Gothic rock', example);
  QUnit.module('Gothabilly', example);
  QUnit.module('Gqom', example);
  QUnit.module('Grebo', example);
  QUnit.module('Gregorian chant', example);
  QUnit.module('Grime', example);
  QUnit.module('Grindcore', example);
  QUnit.module('Griot', example);
  QUnit.module('Groove metal', example);
  QUnit.module('Group Sounds', example);
  QUnit.module('Grunge', example);
  QUnit.module('Grupera', example);
  QUnit.module('Guarania', example);
  QUnit.module('Guajira', example);
  QUnit.module('Gumbe', example);
  QUnit.module('Gunchei', example);
  QUnit.module('Gunka', example);
  QUnit.module('Guoyue', example);
  QUnit.module('Gwo ka', example);
  QUnit.module('Gwo ka moderne', example);
  QUnit.module('Gypsy jazz', example);
  QUnit.module('Gypsy punk', example);
  QUnit.module('Habanera', example);
  QUnit.module('Halling', example);
  QUnit.module('Hambo', example);
  QUnit.module('Hamburger Schule', example);
  QUnit.module('Happy hardcore', example);
  QUnit.module('Haqibah', example);
  QUnit.module('Harawi', example);
  QUnit.module('Hardcore hip hop', example);
  QUnit.module('Hardcore punk', example);
  QUnit.module('Hardcore', example);
  QUnit.module('Hard bop', example);
  QUnit.module('Hard house', example);
  QUnit.module('Hard rock', example);
  QUnit.module('Hardstep', example);
  QUnit.module('Hardstyle', example);
  QUnit.module('Hard trance', example);
  QUnit.module('Harsh noise wall', example);
  QUnit.module('Hasapiko', example);
  QUnit.module('Hát tuồng', example);
  QUnit.module('Heartland rock', example);
  QUnit.module('Heavy hardcore', example);
  QUnit.module('Heavy metal music', example);
  QUnit.module('Hi-NRG', example);
  QUnit.module('Hill country blues', example);
  QUnit.module('Highlife', example);
  QUnit.module('Hiplife', example);
  QUnit.module('Hip hop production', example);
  QUnit.module('Hip hop music', example);
  QUnit.module('Hip house', example);
  QUnit.module('Hindustani classical music', example);
  QUnit.module('Hiragasy', example);
  QUnit.module('Honky-tonk', example);
  QUnit.module('Hokum', example);
  QUnit.module('Honkyoku', example);
  QUnit.module('Hora', example);
  QUnit.module('Hora lungă', example);
  QUnit.module('Hornpipe', example);
  QUnit.module('Horrorcore', example);
  QUnit.module('Horror punk', example);
  QUnit.module('House music', example);
  QUnit.module('Huayño', example);
  QUnit.module('Hula', example);
  QUnit.module('Humppa', example);
  QUnit.module('Hunguhungu', example);
  QUnit.module('Hyangak', example);
  QUnit.module('Hymn', example);
  QUnit.module('Hyphy', example);
  QUnit.module('Icaro', example);
  QUnit.module('Igbo music', example);
  QUnit.module('Illbient', example);
  QUnit.module('Impressionist music', example);
  QUnit.module('Incidental music', example);
  QUnit.module('Indian rock', example);
  QUnit.module('Indietronica', example);
  QUnit.module('Indie folk', example);
  QUnit.module('Independent music', example);
  QUnit.module('Indie pop', example);
  QUnit.module('Indie rock', example);
  QUnit.module('Indigenous music of North America', example);
  QUnit.module('Indigenous rock', example);
  QUnit.module('Indo jazz', example);
  QUnit.module('Industrial death metal', example);
  QUnit.module('Industrial hip hop', example);
  QUnit.module('Industrial music', example);
  QUnit.module('Industrial musical', example);
  QUnit.module('Industrial metal', example);
  QUnit.module('Industrial rock', example);
  QUnit.module('Industrial thrash metal', example);
  QUnit.module('Instrumental', example);
  QUnit.module('Instrumental hip hop', example);
  QUnit.module('Instrumental rock', example);
  QUnit.module('Intelligent dance music', example);
  QUnit.module('Inuit music', example);
  QUnit.module('Irish traditional music', example);
  QUnit.module('Irish rebel music', example);
  QUnit.module('Isicathamiya', example);
  QUnit.module('Islamic music', example);
  QUnit.module('Italo dance', example);
  QUnit.module('Italo disco', example);
  QUnit.module('Italo house', example);
  QUnit.module('J-pop', example);
  QUnit.module('Jaipongan', example);
  QUnit.module('Jam band', example);
  QUnit.module('Jam session', example);
  QUnit.module('Jamaican folk music', example);
  QUnit.module('Jamrieng samai', example);
  QUnit.module('Jangle', example);
  QUnit.module('Japanese rock', example);
  QUnit.module('Japanoise', example);
  QUnit.module('Jarana yucateca', example);
  QUnit.module('Jarocho', example);
  QUnit.module('Jawaiian', example);
  QUnit.module('Jazz', example);
  QUnit.module('Jazzcore', example);
  QUnit.module('Jazz improvisation', example);
  QUnit.module('Jazz-funk', example);
  QUnit.module('Jazz fusion', example);
  QUnit.module('Jazz rap', example);
  QUnit.module('Jazz rock', example);
  QUnit.module('Jegog', example);
  QUnit.module('Jenkka', example);
  QUnit.module('Jesus music', example);
  QUnit.module('Jig', example);
  QUnit.module('Jing ping', example);
  QUnit.module('Jingle', example);
  QUnit.module('Jit', example);
  QUnit.module('Jitterbug', example);
  QUnit.module('Jive', example);
  QUnit.module('Joged', example);
  QUnit.module('Joged bumbung', example);
  QUnit.module('Joik', example);
  QUnit.module('Joropo', example);
  QUnit.module('Jota', example);
  QUnit.module('Jug band', example);
  QUnit.module('Jùjú music', example);
  QUnit.module('Jump blues', example);
  QUnit.module('Jumpstyle', example);
  QUnit.module('Jungle music', example);
  QUnit.module('Junkanoo', example);
  QUnit.module('K-pop', example);
  QUnit.module('Kabuki', example);
  QUnit.module('Kagok', example);
  QUnit.module('Kaiso', example);
  QUnit.module('Kalamatianó', example);
  QUnit.module('Kan ha diskan', example);
  QUnit.module('Kanikapila', example);
  QUnit.module('Kansas City blues', example);
  QUnit.module('Kantrum', example);
  QUnit.module('Kargyraa', example);
  QUnit.module('Kaseko', example);
  QUnit.module('Kachāshī', example);
  QUnit.module('Kawachi ondo', example);
  QUnit.module('Kawaii metal', example);
  QUnit.module('Karaoke', example);
  QUnit.module('Kayōkyoku', example);
  QUnit.module('Kecak', example);
  QUnit.module('Kacapi suling', example);
  QUnit.module('Kertok', example);
  QUnit.module('Khaleeji', example);
  QUnit.module('Khene', example);
  QUnit.module('Khyal', example);
  QUnit.module('Khoomei', example);
  QUnit.module('Kievan chant', example);
  QUnit.module('Kirtan', example);
  QUnit.module('Kiwi rock', example);
  QUnit.module('Kizomba', example);
  QUnit.module('Klapa', example);
  QUnit.module('Klasik', example);
  QUnit.module('Klezmer', example);
  QUnit.module('Kliningan', example);
  QUnit.module('Kolomyjka', example);
  QUnit.module('Komagaku', example);
  QUnit.module('Kpanlogo', example);
  QUnit.module('Krakowiak', example);
  QUnit.module('Krautrock', example);
  QUnit.module('Kriti', example);
  QUnit.module('Kroncong', example);
  QUnit.module('Kuduro', example);
  QUnit.module('Kulintang', example);
  QUnit.module('Kundiman', example);
  QUnit.module('Kvæði', example);
  QUnit.module('Kwaito', example);
  QUnit.module('Kwassa kwassa', example);
  QUnit.module('Kwela', example);
  QUnit.module('Laiko', example);
  QUnit.module('Lambada', example);
  QUnit.module('Landó', example);
  QUnit.module('Latin alternative', example);
  QUnit.module('Latin freestyle', example);
  QUnit.module('Latin jazz', example);
  QUnit.module('Latino hip hop', example);
  QUnit.module('Latin metal', example);
  QUnit.module('Latin music', example);
  QUnit.module('Latin pop', example);
  QUnit.module('Latino punk', example);
  QUnit.module('Latin rock', example);
  QUnit.module('Latin soul', example);
  QUnit.module('Lavani', example);
  QUnit.module('Legényes', example);
  QUnit.module('Letkajenkka', example);
  QUnit.module('Lhamo', example);
  QUnit.module('Lied', example);
  QUnit.module('Light Metal music', example);
  QUnit.module('Light music', example);
  QUnit.module('Liquid funk', example);
  QUnit.module('Lo-fi music', example);
  QUnit.module('Logobi', example);
  QUnit.module('Tehuelche', example);
  QUnit.module('Long song', example);
  QUnit.module('Louisiana blues', example);
  QUnit.module('Lounge music', example);
  QUnit.module('Lovers rock', example);
  QUnit.module('Lowercase', example);
  QUnit.module('Lu', example);
  QUnit.module('Lubbock sound', example);
  QUnit.module('Luk Krung', example);
  QUnit.module('Luk thung', example);
  QUnit.module('Lullaby', example);
  QUnit.module('Lundu', example);
  QUnit.module('M-Base', example);
  QUnit.module('Madchester', example);
  QUnit.module('Madrigal', example);
  QUnit.module('Mafioso rap', example);
  QUnit.module('Mahori', example);
  QUnit.module('Makossa', example);
  QUnit.module('Malhun', example);
  QUnit.module('Maloya', example);
  QUnit.module('Malambo', example);
  QUnit.module('Mambo', example);
  QUnit.module('Manaschi', example);
  QUnit.module('Mandopop', example);
  QUnit.module('Manele', example);
  QUnit.module('Mangue bit', example);
  QUnit.module('Manila Sound', example);
  QUnit.module('Mapouka', example);
  QUnit.module('Marabi', example);
  QUnit.module('Maracatu', example);
  QUnit.module('March', example);
  QUnit.module('Mariachi', example);
  QUnit.module('Marrabenta', example);
  QUnit.module('Martial industrial', example);
  QUnit.module('Martial music', example);
  QUnit.module('Maskanda', example);
  QUnit.module('Marinera', example);
  QUnit.module('Martinetes', example);
  QUnit.module('Mashup', example);
  QUnit.module('Mass', example);
  QUnit.module('Matamuerte', example);
  QUnit.module('Mathcore', example);
  QUnit.module('Math rock', example);
  QUnit.module('Maxixe', example);
  QUnit.module('Mazurka', example);
  QUnit.module('Mbalax', example);
  QUnit.module('Mbaqanga', example);
  QUnit.module('Mbube', example);
  QUnit.module('Meditation music', example);
  QUnit.module('Medieval folk rock', example);
  QUnit.module('Medieval metal', example);
  QUnit.module('Medieval music', example);
  QUnit.module('Mejoranera', example);
  QUnit.module('Melam', example);
  QUnit.module('Melisma', example);
  QUnit.module('Melodic hardcore', example);
  QUnit.module('Melodic metalcore', example);
  QUnit.module('Melodic music', example);
  QUnit.module('Memphis blues', example);
  QUnit.module('Memphis soul', example);
  QUnit.module('Mento', example);
  QUnit.module('Merengue music', example);
  QUnit.module('Merengue típico', example);
  QUnit.module('Méringue', example);
  QUnit.module('Metalcore', example);
  QUnit.module('Mexican rock music', example);
  QUnit.module('Meykhana', example);
  QUnit.module('Mezwed', example);
  QUnit.module('Miami bass', example);
  QUnit.module('Microhouse', example);
  QUnit.module('Microsound', example);
  QUnit.module('Middle Eastern music', example);
  QUnit.module('Midwest hip hop', example);
  QUnit.module('Mini-jazz', example);
  QUnit.module('Minuet', example);
  QUnit.module('Milonga', example);
  QUnit.module("Min'yō", example);
  QUnit.module('Minimal music', example);
  QUnit.module('Minimal techno', example);
  QUnit.module('Minstrel', example);
  QUnit.module('Minneapolis sound', example);
  QUnit.module('Modal jazz', example);
  QUnit.module('Modinha', example);
  QUnit.module('Modern rock', example);
  QUnit.module('Morenada', example);
  QUnit.module('Mor lam', example);
  QUnit.module('Mor lam sing', example);
  QUnit.module('Moombahton', example);
  QUnit.module('Moombahcore', example);
  QUnit.module('Motown sound', example);
  QUnit.module('Montuno', example);
  QUnit.module('Morna', example);
  QUnit.module('Mozambique', example);
  QUnit.module('Mozarabic chant', example);
  QUnit.module('Mugham', example);
  QUnit.module('Mumble rap', example);
  QUnit.module('Murga', example);
  QUnit.module('Musette', example);
  QUnit.module('Mushroom Jazz', example);
  QUnit.module('Music drama', example);
  QUnit.module('Music hall', example);
  QUnit.module('Música criolla', example);
  QUnit.module('Musica llanero', example);
  QUnit.module('Música popular brasileira', example);
  QUnit.module('Musical improvisation', example);
  QUnit.module('Musique concrète', example);
  QUnit.module('Muwashshah', example);
});
