/* global example */
QUnit.module('Edible fruits', function () {
  QUnit.module('Allahabadi Surkha', example);
  QUnit.module('Annona longiflora', example);
  QUnit.module('Annona nutans', example);
  QUnit.module('Annona paludosa', example);
  QUnit.module('Annonaceae', example);
  QUnit.module('Apricot', example);
  QUnit.module('Arbutus unedo', example);
  QUnit.module('Aristotelia serrata', example);
  QUnit.module('Asimina parviflora', example);
  QUnit.module('Asimina triloba', example);
  QUnit.module('Atriplex semibaccata', example);
  QUnit.module('Averrhoa bilimbi', example);
  QUnit.module('Banana', example);
  QUnit.module('Banana melon', example);
  QUnit.module('Banana passionfruit', example);
  QUnit.module('Breadfruit', example);
  QUnit.module('Burchellia', example);
  QUnit.module('Bush tomato', example);
  QUnit.module('Cherimoya', example);
  QUnit.module('Chrysophyllum cainito', example);
  QUnit.module('Citrus australasica', example);
  QUnit.module('Citrus australis', example);
  QUnit.module('Clausena lansium', example);
  QUnit.module('Clymenia (plant)', example);
  QUnit.module('Cornus canadensis', example);
  QUnit.module('Cornus mas', example);
  QUnit.module('Couepia polyandra', example);
  QUnit.module('Crataegus crus-galli', example);
  QUnit.module('Crataegus phaenopyrum', example);
  QUnit.module('Crataegus succulenta', example);
  QUnit.module('Crataegus tanacetifolia', example);
  QUnit.module('Cucumis prophetarum', example);
  QUnit.module('Date-plum', example);
  QUnit.module('Diospyros blancoi', example);
  QUnit.module('Eugenia calycina', example);
  QUnit.module('Eugenia pyriformis', example);
  QUnit.module('Eugenia reinwardtiana', example);
  QUnit.module('Ficus carica', example);
  QUnit.module('Ficus pumila', example);
  QUnit.module('Fig', example);
  QUnit.module('Fruit hat', example);
  QUnit.module('Gac', example);
  QUnit.module('Garcinia assamica', example);
  QUnit.module('Garcinia cowa', example);
  QUnit.module('Garcinia forbesii', example);
  QUnit.module('Garcinia humilis', example);
  QUnit.module('Garcinia lanceifolia', example);
  QUnit.module('Garcinia magnifolia', example);
  QUnit.module('Garcinia pseudoguttifera', example);
  QUnit.module('Gaya melon', example);
  QUnit.module('Glycosmis parviflora', example);
  QUnit.module('Glycosmis pentaphylla', example);
  QUnit.module('Grape', example);
  QUnit.module('Guava', example);
  QUnit.module('Haruka (citrus)', example);
  QUnit.module('Honeydew (melon)', example);
  QUnit.module('Irvingia', example);
  QUnit.module('Kajari melon', example);
  QUnit.module('Kanpei', example);
  QUnit.module('Kawachi Bankan', example);
  QUnit.module('Kinkoji unshiu', example);
  QUnit.module('Kiwifruit', example);
  QUnit.module('Kobayashi mikan', example);
  QUnit.module('Koji orange', example);
  QUnit.module('Kolkhoznitsa melon', example);
  QUnit.module('Kuchinotsu No. 37', example);
  QUnit.module('Leycesteria formosa', example);
  QUnit.module('Licania platypus', example);
  QUnit.module('Litsea garciae', example);
  QUnit.module('Longan', example);
  QUnit.module('Lonicera caerulea', example);
  QUnit.module('Lucuma', example);
  QUnit.module('Lychee', example);
  QUnit.module('Mahonia fremontii', example);
  QUnit.module('Mango', example);
  QUnit.module('Mangosteen', example);
  QUnit.module('Mayhaw', example);
  QUnit.module('Mespilus germanica', example);
  QUnit.module('Mirza melon', example);
  QUnit.module('Morinda citrifolia', example);
  QUnit.module('Morus nigra', example);
  QUnit.module('Nectaplum', example);
  QUnit.module('Nephelium chryseum', example);
  QUnit.module('Nephelium xerospermoides', example);
  QUnit.module('Pandanus tectorius', example);
  QUnit.module('Passiflora', example);
  QUnit.module('Passiflora ligularis', example);
  QUnit.module('Passiflora tarminiana', example);
  QUnit.module('Persimmon', example);
  QUnit.module('Physalis pubescens', example);
  QUnit.module('Pineapple', example);
  QUnit.module('Pitaya', example);
  QUnit.module('Pomegranate', example);
  QUnit.module('Pompia', example);
  QUnit.module('Produce', example);
  QUnit.module('Prunus americana', example);
  QUnit.module('Psidium cattleyanum', example);
  QUnit.module('Pulasan', example);
  QUnit.module('Quince', example);
  QUnit.module('Rambutan', example);
  QUnit.module('Rhus typhina', example);
  QUnit.module('Ribes americanum', example);
  QUnit.module('Ribes montigenum', example);
  QUnit.module('Rubus spectabilis', example);
  QUnit.module('Rubus tricolor', example);
  QUnit.module('Rubus ulmifolius', example);
  QUnit.module('Sambucus nigra', example);
  QUnit.module('Sandoricum koetjape', example);
  QUnit.module('Seedless fruit', example);
  QUnit.module('Sonneratia caseolaris', example);
  QUnit.module('Sorbus americana', example);
  QUnit.module('Stone fruits', example);
  QUnit.module('Sugar-apple', example);
  QUnit.module('Sunflower seed', example);
  QUnit.module('Sycamine', example);
  QUnit.module('Tamarillo', example);
  QUnit.module('Viburnum edule', example);
  QUnit.module('Volkamer lemon', example);
  QUnit.module('Watermelon', example);
  QUnit.module('White sapote', example);
  QUnit.module('Xocotl', example);
});
