/* global example */
QUnit.module('Fruit dishes', function () {
  QUnit.module('Açaí na tigela', example);
  QUnit.module('Ashure', example);
  QUnit.module('Asinan', example);
  QUnit.module('Avakaya', example);
  QUnit.module('Banbury cake', example);
  QUnit.module('Black bun', example);
  QUnit.module('Boerenjongens', example);
  QUnit.module('Bombe glacée', example);
  QUnit.module('Candle salad', example);
  QUnit.module('Chakka prathaman', example);
  QUnit.module('Chakkavaratti', example);
  QUnit.module('Charlotte (cake)', example);
  QUnit.module('Chorley cake', example);
  QUnit.module('Clafoutis', example);
  QUnit.module('Cobbler (food)', example);
  QUnit.module('Compote', example);
  QUnit.module('Cranachan', example);
  QUnit.module('Crema de fruta', example);
  QUnit.module('Crisp (dessert)', example);
  QUnit.module('Crumble', example);
  QUnit.module('Cumberland rum nicky', example);
  QUnit.module('Daechu-gom', example);
  QUnit.module('Dolma', example);
  QUnit.module('Donauwelle', example);
  QUnit.module('Duff (dessert)', example);
  QUnit.module('Eccles cake', example);
  QUnit.module('Es buah', example);
  QUnit.module('Es campur', example);
  QUnit.module('Es teler', example);
  QUnit.module('Eton mess', example);
  QUnit.module('Flaugnarde', example);
  QUnit.module('Flies graveyard', example);
  QUnit.module('Frogeye salad', example);
  QUnit.module('Fruit butter', example);
  QUnit.module('Fruit curd', example);
  QUnit.module('Fruit fool', example);
  QUnit.module('Fruit hat (pudding)', example);
  QUnit.module('Fruit ketchup', example);
  QUnit.module('Fruit salad', example);
  QUnit.module('Fruit whip', example);
  QUnit.module('Fruitcake', example);
  QUnit.module('Grape syrup', example);
  QUnit.module('Güllaç', example);
  QUnit.module('Gwapyeon', example);
  QUnit.module('Hagebuttenmark', example);
  QUnit.module('Hakuto jelly', example);
  QUnit.module('Hwachae', example);
  QUnit.module('Kirschenmichel', example);
  QUnit.module('Kompot', example);
  QUnit.module('Krentjebrij', example);
  QUnit.module('Lörtsy', example);
  QUnit.module('Malvern pudding', example);
  QUnit.module('Manchester tart', example);
  QUnit.module('Mango cake', example);
  QUnit.module('Mango float', example);
  QUnit.module('Mango pudding', example);
  QUnit.module('Marillenknödel', example);
  QUnit.module('Mincemeat', example);
  QUnit.module('Multekrem', example);
  QUnit.module('Murabba', example);
  QUnit.module('Peach Melba', example);
  QUnit.module('Peaches and cream', example);
  QUnit.module('Persimmon pudding', example);
  QUnit.module('Pestil', example);
  QUnit.module("Po'e", example);
  QUnit.module('Poi', example);
  QUnit.module('Pork chops and applesauce', example);
  QUnit.module('Qubani-ka-Meetha', example);
  QUnit.module('Relish', example);
  QUnit.module('Rødgrød', example);
  QUnit.module('Rojak', example);
  QUnit.module('Rose hip soup', example);
  QUnit.module('Rumtopf', example);
  QUnit.module('Seafoam salad', example);
  QUnit.module('Spotted dick', example);
  QUnit.module('Summer pudding', example);
  QUnit.module('Takihi', example);
  QUnit.module('Tanghulu', example);
  QUnit.module('Tarte des Alpes', example);
  QUnit.module('Tilslørte bondepiker', example);
  QUnit.module('Tomato jam', example);
  QUnit.module('Tutti frutti', example);
  QUnit.module('Vispipuuro', example);
  QUnit.module('Xi gua lao', example);
});

QUnit.module('Wikipedia language editions', function () {
  QUnit.module('Over 1 million articles', function () {
    QUnit.module('Polski', example);
    QUnit.module('العربية', example);
    QUnit.module('Deutsch', example);
    QUnit.module('English', example);
    QUnit.module('Español', example);
    QUnit.module('Français', example);
    QUnit.module('Italiano', example);
    QUnit.module('مصرى', example);
    QUnit.module('Nederlands', example);
    QUnit.module('日本語', example);
    QUnit.module('Português', example);
    QUnit.module('Русский', example);
    QUnit.module('Sinugboanong Binisaya', example);
    QUnit.module('Svenska', example);
    QUnit.module('Українська', example);
    QUnit.module('Tiếng Việt', example);
    QUnit.module('Winaray', example);
    QUnit.module('中文', example);
  });

  QUnit.module('Over 100,000 articles', function () {
    QUnit.module('Afrikaans', example);
    QUnit.module('Slovenčina', example);
    QUnit.module('Asturianu', example);
    QUnit.module('Azərbaycanca', example);
    QUnit.module('Български', example);
    QUnit.module('Bân-lâm-gú / Hō-ló-oē', example);
    QUnit.module('বাংলা', example);
    QUnit.module('Беларуская', example);
    QUnit.module('Català', example);
    QUnit.module('Čeština', example);
    QUnit.module('Cymraeg', example);
    QUnit.module('Dansk', example);
    QUnit.module('Eesti', example);
    QUnit.module('Ελληνικά', example);
    QUnit.module('Esperanto', example);
    QUnit.module('Euskara', example);
    QUnit.module('فارسی', example);
    QUnit.module('Galego', example);
    QUnit.module('한국어', example);
    QUnit.module('Հայերեն', example);
    QUnit.module('हिन्दी', example);
    QUnit.module('Hrvatski', example);
    QUnit.module('Bahasa Indonesia', example);
    QUnit.module('עברית', example);
    QUnit.module('ქართული', example);
    QUnit.module('Latina', example);
    QUnit.module('Latviešu', example);
    QUnit.module('Lietuvių', example);
    QUnit.module('Magyar', example);
    QUnit.module('Македонски', example);
    QUnit.module('Bahasa Melayu', example);
    QUnit.module('Bahaso Minangkabau', example);
    QUnit.module('Norsk', example);
    QUnit.module('bokmålnynorsk', example);
    QUnit.module('Нохчийн', example);
    QUnit.module('Oʻzbekcha / Ўзбекча', example);
    QUnit.module('Қазақша / Qazaqşa / قازاقشا', example);
    QUnit.module('Română', example);
    QUnit.module('Simple English', example);
    QUnit.module('Slovenščina', example);
    QUnit.module('Српски / Srpski', example);
    QUnit.module('Srpskohrvatski / Српскохрватски', example);
    QUnit.module('Suomi', example);
    QUnit.module('தமிழ்', example);
    QUnit.module('Татарча / Tatarça', example);
    QUnit.module('ภาษาไทย', example);
    QUnit.module('Тоҷикӣ', example);
    QUnit.module('تۆرکجه', example);
    QUnit.module('Türkçe', example);
    QUnit.module('اردو', example);
    QUnit.module('Volapük', example);
    QUnit.module('粵語', example);
    QUnit.module('မြန်မာဘာသာ', example);
  });
  QUnit.module('Over 10,000 articles', function () {
    QUnit.module('Bahsa Acèh', example);
    QUnit.module('Alemannisch', example);
    QUnit.module('አማርኛ', example);
    QUnit.module('Aragonés', example);
    QUnit.module('Basa Bali', example);
    QUnit.module('Basa Banyumasan', example);
    QUnit.module('Башҡортса', example);
    QUnit.module('Беларуская (Тарашкевіца)', example);
    QUnit.module('Bikol Central', example);
    QUnit.module('বিষ্ণুপ্রিয়া মণিপুরী', example);
    QUnit.module('Boarisch', example);
    QUnit.module('Bosanski', example);
    QUnit.module('Brezhoneg', example);
    QUnit.module('Чӑвашла', example);
    QUnit.module('Diné Bizaad', example);
    QUnit.module('Emigliàn–Rumagnòl', example);
    QUnit.module('Fiji Hindi', example);
    QUnit.module('Føroyskt', example);
    QUnit.module('Frysk', example);
    QUnit.module('Gaeilge', example);
    QUnit.module('Gàidhlig', example);
    QUnit.module('ગુજરાતી', example);
    QUnit.module('Hausa', example);
    QUnit.module('Hornjoserbsce', example);
    QUnit.module('Ido', example);
    QUnit.module('Ilokano', example);
    QUnit.module('Interlingua', example);
    QUnit.module('Ирон', example);
    QUnit.module('Íslenska', example);
    QUnit.module('Jawa', example);
    QUnit.module('ಕನ್ನಡ', example);
    QUnit.module('Kreyòl Ayisyen', example);
    QUnit.module('Kurdî / كوردی', example);
    QUnit.module('کوردیی ناوەندی', example);
    QUnit.module('Кыргызча', example);
    QUnit.module('Кырык мары', example);
    QUnit.module('Lëtzebuergesch', example);
    QUnit.module('Limburgs', example);
    QUnit.module('Lombard', example);
    QUnit.module('Lìgure', example);
    QUnit.module('मैथिली', example);
    QUnit.module('Malagasy', example);
    QUnit.module('മലയാളം', example);
    QUnit.module('文言', example);
    QUnit.module('मराठी', example);
    QUnit.module('მარგალური', example);
    QUnit.module('مازِرونی', example);
    QUnit.module('Mìng-dĕ̤ng-ngṳ̄ / 閩東語', example);
    QUnit.module('Монгол', example);
    QUnit.module('Napulitano', example);
    QUnit.module('नेपाल भाषा', example);
    QUnit.module('नेपाली', example);
    QUnit.module('Nordfriisk', example);
    QUnit.module('Occitan', example);
    QUnit.module('Олык марий', example);
    QUnit.module('ଓଡି଼ଆ', example);
    QUnit.module('অসমীযা়', example);
    QUnit.module('ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)', example);
    QUnit.module('پنجابی (شاہ مکھی)', example);
    QUnit.module('پښتو', example);
    QUnit.module('Piemontèis', example);
    QUnit.module('Plattdüütsch', example);
    QUnit.module('Qırımtatarca', example);
    QUnit.module('Runa Simi', example);
    QUnit.module('संस्कृतम्', example);
    QUnit.module('Саха Тыла', example);
    QUnit.module('Scots', example);
    QUnit.module('Shqip', example);
    QUnit.module('Sicilianu', example);
    QUnit.module('සිංහල', example);
    QUnit.module('سنڌي', example);
    QUnit.module('Ślůnski', example);
    QUnit.module('Basa Sunda', example);
    QUnit.module('Kiswahili', example);
    QUnit.module('Tagalog', example);
    QUnit.module('ၽႃႇသႃႇတႆး', example);
    QUnit.module('తెలుగు', example);
    QUnit.module('ᨅᨔ ᨕᨙᨁᨗ / Basa Ugi', example);
    QUnit.module('Vèneto', example);
    QUnit.module('Walon', example);
    QUnit.module('吳語', example);
    QUnit.module('ייִדיש', example);
    QUnit.module('Yorùbá', example);
    QUnit.module('Zazaki', example);
    QUnit.module('Žemaitėška', example);
    QUnit.module('isiZulu', example);
  });
  QUnit.module('Over 1,000 articles', function () {
    QUnit.module('Dzhudezmo / לאדינו', example);
    QUnit.module('Адыгэбзэ', example);
    QUnit.module('Ænglisc', example);
    QUnit.module('Anarâškielâ', example);
    QUnit.module('аԥсшәа', example);
    QUnit.module('Արեւմտահայերէն', example);
    QUnit.module('Armãneashce', example);
    QUnit.module('Arpitan', example);
    QUnit.module('ܐܬܘܪܝܐ', example);
    QUnit.module('Avañe’ẽ', example);
    QUnit.module('Авар', example);
    QUnit.module('Aymar', example);
    QUnit.module('Bahasa Banjar', example);
    QUnit.module('भोजपुरी', example);
    QUnit.module('Bislama', example);
    QUnit.module('བོད་ཡིག', example);
    QUnit.module('Буряад', example);
    QUnit.module('Chavacano de Zamboanga', example);
    QUnit.module('Corsu', example);
    QUnit.module('Vahcuengh / 話僮', example);
    QUnit.module('Dagbanli', example);
    QUnit.module('الدارجة', example);
    QUnit.module('Davvisámegiella', example);
    QUnit.module('Deitsch', example);
    QUnit.module('ދިވެހިބަސް', example);
    QUnit.module('Dolnoserbski', example);
    QUnit.module('Эрзянь', example);
    QUnit.module('Estremeñu', example);
    QUnit.module('Furlan', example);
    QUnit.module('Gaelg', example);
    QUnit.module('Gagauz', example);
    QUnit.module('ГӀалгӀай', example);
    QUnit.module('Gĩkũyũ', example);
    QUnit.module('گیلکی', example);
    QUnit.module('贛語', example);
    QUnit.module('Hak-kâ-ngî / 客家語', example);
    QUnit.module('Хальмг', example);
    QUnit.module('ʻŌlelo Hawaiʻi', example);
    QUnit.module('Igbo', example);
    QUnit.module('Interlingue', example);
    QUnit.module('Kabɩyɛ', example);
    QUnit.module('Kapampangan', example);
    QUnit.module('Kaszëbsczi', example);
    QUnit.module('Kernewek', example);
    QUnit.module('ភាសាខ្មែរ', example);
    QUnit.module('Kinyarwanda', example);
    QUnit.module('Коми', example);
    QUnit.module('Перем коми', example);
    QUnit.module('Kongo', example);
    QUnit.module('कोंकणी / Konknni', example);
    QUnit.module('كٲشُر', example);
    QUnit.module('Kriyòl Gwiyannen', example);
    QUnit.module('ພາສາລາວ', example);
    QUnit.module('Лакку', example);
    QUnit.module('Latgaļu', example);
    QUnit.module('Лезги', example);
    QUnit.module('Li Niha', example);
    QUnit.module('Lingála', example);
    QUnit.module('lojban', example);
    QUnit.module('Luganda', example);
    QUnit.module('Malti', example);
    QUnit.module('Māori', example);
    QUnit.module('Twi', example);
    QUnit.module('Mirandés', example);
    QUnit.module('Мокшень', example);
    QUnit.module('ဘာသာ မန်', example);
    QUnit.module('ߒߞߏ', example);
    QUnit.module('Na Vosa Vaka-Viti', example);
    QUnit.module('Nāhuatlahtōlli', example);
    QUnit.module('Dorerin Naoero', example);
    QUnit.module('Nedersaksisch', example);
    QUnit.module('Nouormand / Normaund', example);
    QUnit.module('Novial', example);
    QUnit.module('Afaan Oromoo', example);
    QUnit.module('पालि', example);
    QUnit.module('Pangasinán', example);
    QUnit.module('Papiamentu', example);
    QUnit.module('Pfälzisch', example);
    QUnit.module('Picard', example);
    QUnit.module('Къарачай–малкъар', example);
    QUnit.module('Qaraqalpaqsha', example);
    QUnit.module('Ripoarisch', example);
    QUnit.module('Rumantsch', example);
    QUnit.module('Русиньскый', example);
    QUnit.module('Gagana Sāmoa', example);
    QUnit.module('ᱥᱟᱱᱛᱟᱲᱤ', example);
    QUnit.module('Sardu', example);
    QUnit.module('Seediq', example);
    QUnit.module('Seeltersk', example);
    QUnit.module('Sesotho sa Leboa', example);
    QUnit.module('ChiShona', example);
    QUnit.module('Словѣ́ньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ', example);
    QUnit.module('Soomaaliga', example);
    QUnit.module('Sranantongo', example);
    QUnit.module('Taqbaylit', example);
    QUnit.module('Tarandíne', example);
    QUnit.module('Tetun', example);
    QUnit.module('Tok Pisin', example);
    QUnit.module('faka Tonga', example);
    QUnit.module('ᏣᎳᎩ', example);
    QUnit.module('chiTumbuka', example);
    QUnit.module('Türkmençe', example);
    QUnit.module('Тыва дыл', example);
    QUnit.module('Удмурт', example);
    QUnit.module('ئۇيغۇرچه', example);
    QUnit.module('Vepsän', example);
    QUnit.module('Võro', example);
    QUnit.module('West-Vlams', example);
    QUnit.module('Wolof', example);
    QUnit.module('isiXhosa', example);
    QUnit.module('Zeêuws', example);
    QUnit.module('Reo tahiti', example);
  });
  QUnit.module('Over 100 articles', function () {
    QUnit.module('Akan', example);
    QUnit.module('Bamanankan', example);
    QUnit.module('Chamoru', example);
    QUnit.module('Chichewa', example);
    QUnit.module('Eʋegbe', example);
    QUnit.module('Fulfulde', example);
    QUnit.module('𐌲𐌿𐍄𐌹𐍃𐌺', example);
    QUnit.module('ᐃᓄᒃᑎᑐᑦ / Inuktitut', example);
    QUnit.module('Iñupiak', example);
    QUnit.module('Kalaallisut', example);
    QUnit.module('Madhurâ', example);
    QUnit.module('Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ', example);
    QUnit.module('Norfuk / Pitkern', example);
    QUnit.module('Pangcah', example);
    QUnit.module('pinayuanan', example);
    QUnit.module('Ποντιακά', example);
    QUnit.module('རྫོང་ཁ', example);
    QUnit.module('romani čhib', example);
    QUnit.module('Kirundi', example);
    QUnit.module('Sängö', example);
    QUnit.module('Sesotho', example);
    QUnit.module('Setswana', example);
    QUnit.module('SiSwati', example);
    QUnit.module('Thuɔŋjäŋ', example);
    QUnit.module('Tsėhesenėstsestotse', example);
    QUnit.module('Xitsonga', example);
    QUnit.module('ትግርኛ', example);
    QUnit.module('Tshivenḓa', example);
  });
});
